### ISSUE TITLE
Rename Projects

### ISSUE THREAD

**Issue by TobyMaxham** [Minneola/Foo#1]
We have to think about renaming the project. It could get famous xD

**Comment by NorbertFox** [comment]
@TobyMaxham wir sind die einzigen hier! Schreib deutsch...
-> Das wird nicht bekannt!

**Comment by riddg** [comment]
What about to call the framework 'base' and this repo 'site'?

**Comment by TobyMaxham** [comment]
Hello Riddley,
we are about to make a poll to this issue. We will add your suggsession to the poll.

Thanks

Von meinem iPhone gesendet

Am 12.08.2015 um 10:47 schrieb Riddley Sole <notifications@github.com<mailto:notifications@github.com>>:

What about to call the framework 'base' and this repo 'site'?
