### ISSUE TITLE
Smile: ohne Slash

### ISSUE THREAD

**Issue by starkh** [Minneola/Foo#2]
Wenn ich etwas schreiben wie:

``` php
Smile::get('dashboard', 'SiffController@index');
```

Dann kommt der Fehler:
Warning: call_user_func() expects parameter 1 to be a valid callback, function 'SiffController@index' not found or invalid function name.

Da ist noch was im Framework falsch?

**Comment by NorbertFox** [comment]
Fixed: https://github.com/Minneola/TestForTransfer/commit/1732d55d13c45acdd8f8dec10fa33a1436fe91c0
