### ISSUE TITLE
Schleifen gehen nicht

### ISSUE THREAD

**Issue by starkh** [Minneola/Foo#3]
for ist wichtig

```
@for($i=1;$1<10;$i++)
    Irgendwas <br />
@endfor
```

Und while...

```
@while()
@endwile
```

**Comment by NorbertFox** [comment]
Das soll Heiko machen!

**Comment by NorbertFox** [comment]
Fixed: https://github.com/Minneola/TestForTransfer/commit/4a2276e011a527daea1215b1318c8b2f8bdbd215

**Comment by TobyMaxham** [comment]
Hier der richtige Fix: https://github.com/Minneola/TestForTransfer/commit/bdd3542cea104b191c6aa5490a95a442e097c018
