### ISSUE TITLE
File Handling

### ISSUE THREAD

**Issue by starkh** [Minneola/Foo#4]
Fehlt auch

**Comment by NorbertFox** [comment]
Das macht Toby.

**Comment by NorbertFox** [comment]
Am besten in Core

**Comment by TobyMaxham** [comment]
File Handling jetzt schon ?

**Comment by TobyMaxham** [comment]
Done. Sogar mit Alias.
https://github.com/Minneola/TestForTransfer/commit/9c69cf71a601dea6703b5ec31bf385e3d90a68a9

**Comment by starkh** [comment]
Warum kein Package

Sent using CloudMagic [https://cloudmagic.com/k/d/mailapp?ct=pi&cv=6.0.64&pv=8.1]
On Di., Aug. 4, 2015 at 2:44 vorm., Minneola/Foo
reply@reply.github.com
wrote:
Am besten in Core

—
Reply to this email directly or view it on GitHub
[https://github.com/Minneola/Foo/issues/4#issuecomment-127442502] .[https://github.com/notifications/beacon/AM_7zPjiq_vgJ5a9k-nIxGKKVOrI9bYLks5okAJugaJpZM4Fk-Gy.gif]

**Comment by TobyMaxham** [comment]
https://github.com/Minneola/TestForTransfer/issues/15
